alter table `center`.`center_0_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_0_loginlog` add index order_id(order_id);
alter table `center`.`center_1_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_1_loginlog` add index order_id(order_id);
alter table `center`.`center_2_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_2_loginlog` add index order_id(order_id);
alter table `center`.`center_3_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_3_loginlog` add index order_id(order_id);
alter table `center`.`center_4_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_4_loginlog` add index order_id(order_id);
alter table `center`.`center_5_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_5_loginlog` add index order_id(order_id);
alter table `center`.`center_6_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_6_loginlog` add index order_id(order_id);
alter table `center`.`center_7_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_7_loginlog` add index order_id(order_id);
alter table `center`.`center_8_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_8_loginlog` add index order_id(order_id);
alter table `center`.`center_9_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_9_loginlog` add index order_id(order_id);
alter table `center`.`center_10_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_10_loginlog` add index order_id(order_id);
alter table `center`.`center_11_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_11_loginlog` add index order_id(order_id);
alter table `center`.`center_12_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_12_loginlog` add index order_id(order_id);
alter table `center`.`center_13_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_13_loginlog` add index order_id(order_id);
alter table `center`.`center_14_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_14_loginlog` add index order_id(order_id);
alter table `center`.`center_15_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_15_loginlog` add index order_id(order_id);
alter table `center`.`center_16_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_16_loginlog` add index order_id(order_id);
alter table `center`.`center_17_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_17_loginlog` add index order_id(order_id);
alter table `center`.`center_18_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_18_loginlog` add index order_id(order_id);
alter table `center`.`center_19_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_19_loginlog` add index order_id(order_id);
alter table `center`.`center_20_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_20_loginlog` add index order_id(order_id);
alter table `center`.`center_21_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_21_loginlog` add index order_id(order_id);
alter table `center`.`center_22_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_22_loginlog` add index order_id(order_id);
alter table `center`.`center_23_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_23_loginlog` add index order_id(order_id);
alter table `center`.`center_24_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_24_loginlog` add index order_id(order_id);
alter table `center`.`center_25_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_25_loginlog` add index order_id(order_id);
alter table `center`.`center_26_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_26_loginlog` add index order_id(order_id);
alter table `center`.`center_27_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_27_loginlog` add index order_id(order_id);
alter table `center`.`center_28_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_28_loginlog` add index order_id(order_id);
alter table `center`.`center_29_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_29_loginlog` add index order_id(order_id);
alter table `center`.`center_30_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_30_loginlog` add index order_id(order_id);
alter table `center`.`center_31_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_31_loginlog` add index order_id(order_id);
alter table `center`.`center_32_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_32_loginlog` add index order_id(order_id);
alter table `center`.`center_33_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_33_loginlog` add index order_id(order_id);
alter table `center`.`center_34_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_34_loginlog` add index order_id(order_id);
alter table `center`.`center_35_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_35_loginlog` add index order_id(order_id);
alter table `center`.`center_36_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_36_loginlog` add index order_id(order_id);
alter table `center`.`center_37_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_37_loginlog` add index order_id(order_id);
alter table `center`.`center_38_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_38_loginlog` add index order_id(order_id);
alter table `center`.`center_39_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_39_loginlog` add index order_id(order_id);
alter table `center`.`center_40_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_40_loginlog` add index order_id(order_id);
alter table `center`.`center_41_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_41_loginlog` add index order_id(order_id);
alter table `center`.`center_42_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_42_loginlog` add index order_id(order_id);
alter table `center`.`center_43_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_43_loginlog` add index order_id(order_id);
alter table `center`.`center_44_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_44_loginlog` add index order_id(order_id);
alter table `center`.`center_45_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_45_loginlog` add index order_id(order_id);
alter table `center`.`center_46_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_46_loginlog` add index order_id(order_id);
alter table `center`.`center_47_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_47_loginlog` add index order_id(order_id);
alter table `center`.`center_48_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_48_loginlog` add index order_id(order_id);
alter table `center`.`center_49_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_49_loginlog` add index order_id(order_id);
alter table `center`.`center_50_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_50_loginlog` add index order_id(order_id);
alter table `center`.`center_666_loginlog` add(`order_id` varchar(25) not null default '0' comment '商户订单号');
alter table `center`.`center_666_loginlog` add index order_id(order_id);