alter table center.center_0_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_0_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_1_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_1_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_2_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_2_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_3_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_3_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_4_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_4_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_5_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_5_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_6_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_6_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_7_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_7_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_8_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_8_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_9_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_9_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_10_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_10_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_11_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_11_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_12_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_12_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_13_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_13_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_14_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_14_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_15_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_15_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_16_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_16_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_17_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_17_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_18_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_18_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_19_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_19_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_20_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_20_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_21_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_21_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_22_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_22_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_23_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_23_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_24_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_24_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_25_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_25_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_26_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_26_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_27_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_27_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_28_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_28_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_29_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_29_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_30_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_30_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_31_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_31_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_32_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_32_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_33_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_33_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_34_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_34_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_35_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_35_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_36_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_36_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_37_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_37_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_38_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_38_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_39_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_39_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_40_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_40_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_41_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_41_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_42_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_42_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_43_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_43_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_44_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_44_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_45_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_45_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_46_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_46_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_47_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_47_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_48_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_48_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_49_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_49_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_50_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_50_order add index type_id(type_id),add index platform_and_type(platform_and_type);
alter table center.center_666_order add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");	alter table center.center_666_order add index type_id(type_id),add index platform_and_type(platform_and_type);
/*  
SELECT DISTINCT 
	concat( 'alter table ', TABLE_NAME, ' add (type_id int(5) NOT NULL DEFAULT 0 comment "games类型id",platform_and_type varchar(7)  not null default 0 comment "平台ID和games的类型");' ) AS string ,concat(
'alter table ',TABLE_NAME,' add index type_id(type_id),add index platform_and_type(platform_and_type);'
)  as string2
FROM
	information_schema.COLUMNS 
WHERE
	table_name LIKE ( '%_order' )   
ORDER BY
	REPLACE ( REPLACE ( table_name, 'center_', '' ), '_order', '' ) ASC
     */
