alter table `center`.`center_0_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_0_user` add index balance(balance);
alter table `center`.`center_1_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_1_user` add index balance(balance);
alter table `center`.`center_2_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_2_user` add index balance(balance);
alter table `center`.`center_3_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_3_user` add index balance(balance);
alter table `center`.`center_4_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_4_user` add index balance(balance);
alter table `center`.`center_5_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_5_user` add index balance(balance);
alter table `center`.`center_6_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_6_user` add index balance(balance);
alter table `center`.`center_7_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_7_user` add index balance(balance);
alter table `center`.`center_8_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_8_user` add index balance(balance);
alter table `center`.`center_9_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_9_user` add index balance(balance);
alter table `center`.`center_10_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_10_user` add index balance(balance);
alter table `center`.`center_11_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_11_user` add index balance(balance);
alter table `center`.`center_12_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_12_user` add index balance(balance);
alter table `center`.`center_13_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_13_user` add index balance(balance);
alter table `center`.`center_14_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_14_user` add index balance(balance);
alter table `center`.`center_15_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_15_user` add index balance(balance);
alter table `center`.`center_16_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_16_user` add index balance(balance);
alter table `center`.`center_17_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_17_user` add index balance(balance);
alter table `center`.`center_18_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_18_user` add index balance(balance);
alter table `center`.`center_19_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_19_user` add index balance(balance);
alter table `center`.`center_20_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_20_user` add index balance(balance);
alter table `center`.`center_21_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_21_user` add index balance(balance);
alter table `center`.`center_22_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_22_user` add index balance(balance);
alter table `center`.`center_23_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_23_user` add index balance(balance);
alter table `center`.`center_24_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_24_user` add index balance(balance);
alter table `center`.`center_25_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_25_user` add index balance(balance);
alter table `center`.`center_26_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_26_user` add index balance(balance);
alter table `center`.`center_27_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_27_user` add index balance(balance);
alter table `center`.`center_28_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_28_user` add index balance(balance);
alter table `center`.`center_29_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_29_user` add index balance(balance);
alter table `center`.`center_30_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_30_user` add index balance(balance);
alter table `center`.`center_31_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_31_user` add index balance(balance);
alter table `center`.`center_32_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_32_user` add index balance(balance);
alter table `center`.`center_33_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_33_user` add index balance(balance);
alter table `center`.`center_34_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_34_user` add index balance(balance);
alter table `center`.`center_35_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_35_user` add index balance(balance);
alter table `center`.`center_36_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_36_user` add index balance(balance);
alter table `center`.`center_37_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_37_user` add index balance(balance);
alter table `center`.`center_38_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_38_user` add index balance(balance);
alter table `center`.`center_39_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_39_user` add index balance(balance);
alter table `center`.`center_40_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_40_user` add index balance(balance);
alter table `center`.`center_41_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_41_user` add index balance(balance);
alter table `center`.`center_42_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_42_user` add index balance(balance);
alter table `center`.`center_43_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_43_user` add index balance(balance);
alter table `center`.`center_44_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_44_user` add index balance(balance);
alter table `center`.`center_45_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_45_user` add index balance(balance);
alter table `center`.`center_46_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_46_user` add index balance(balance);
alter table `center`.`center_47_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_47_user` add index balance(balance);
alter table `center`.`center_48_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_48_user` add index balance(balance);
alter table `center`.`center_49_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_49_user` add index balance(balance);
alter table `center`.`center_50_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table `center`.`center_50_user` add index balance(balance);
alter table `center`.`center_666_user` add(`balance` decimal(14,4) NOT NULL DEFAULT 0.0000 COMMENT '用户余额' );
alter table  `center`.`center_666_user` add index balance(balance);